name = "pack-de-recibidas"
compatibility_date = "2024-01-01"
pages_build_output_dir = "out"

[[kv_namespaces]]
binding = "RATELIMIT_KV"
id = "facf29bfc5d84743a286cda39d16e845"

[[r2_buckets]]
binding = "DESIGNS_R2"
bucket_name = "pack-designs"
